[![Review Assignment Due Date](https://classroom.github.com/assets/deadline-readme-button-24ddc0f5d75046c5622901739e7c5dd533143b0c8e959d652212380cedb1ea36.svg)](https://classroom.github.com/a/G801g4IR)
= Gestionnaire de Fichiers en Commandes en Ligne avec Annotations

MOUSSAOUI, Iness, 22006171,51

DJEBBOUR , Elias ,22108396, 50 

https://github.com/ensYeh/miniprojet-grp-51_50

L'objet de ce mini-projet est de développer un https://fr.wikipedia.org/wiki/Gestionnaire_de_fichier[gestionnaire de fichiers] en commande en ligne. Le gestionnaire de fichier s'appuie sur le système de fichier de votre système d'exploitation. Le gestionnaire de fichier doit offrir la possibilité d'annoter les éléments contenus dans un répertoire (i.e.fichiers, répertoires).
Vous devrez respecter les contraintes fonctionnelles et techniques mentionnées ci-dessous.

[IMPORTANT]
====
Vous respecterez les contraintes suivantes:

* Ce mini-projet est à réaliser en Java par groupe de 2 étudiants.
  - les 2 étudiants doivent coopérer à travers un même git. Un des deux étudiants devra permettre à l'autre d'utiliser son git.
* Il devra comporter une documentation dans ce git.
  - La documentation devra décrire l'usage de l'application (_manuel utilisateur_) ainsi que la conception du jeu (_manuel technique_).
  - La documentation doit être un fichier .md ou .adoc et accessible depuis le `git`
* Vous utiliserez `git` en effectuant des commits réguliers comportant des messages informatifs. L'usage des "pull requests" est également fortement conseillé, montrant ainsi votre collaboration au sein du groupe. 
* Le _build_ sera assuré par Maven et plus précisément Maven wrapper (déjà intégré dans le projet).
Aucune manipulation en dehors de Maven ne devra être nécessaire.
* La version de Java à utiliser est la https://adoptium.net/[version 17].
* Le _build_ devra intégrer `checkstyle` pour la vérification des règles de codages Google.
Le projet devra donc les respecter.
`checkstyle` devra être exécuté automatiquement durant la phase `validate` du cycle de vie par défaut.
* Des tests unitaires https://junit.org/junit5/docs/current/user-guide/[JUnit 5] (version https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter/5.9.1[_5.9.1_]) devront être disponibles pour la plupart des méthodes développées.
* Un outil de https://fr.wikipedia.org/wiki/Couverture_de_code[_Code Coverage_] devra être intégré au _build_
* Les fonctionnalités du langage Java devront être utilisées au mieux (POO, exceptions, librairie de collections, I/O, …).
* L'application devra pouvoir être exécutée à partir d'un `jar` incluant toutes les dépendances.
====

== Description du gestionnaire de fichiers
* L'interface proposera une visualisation du contenu d'un répertoire en mode texte. A chaque élément du répertoire (**ER**), on associera un numero (**NER**) permettant de le designer lors de l'utilisation d'une des commandes définies ci-dessous.

* Les actions de l'utilisateur seront saisies au clavier sous la forme `[<NER>] [<commande>] [<nom>]`. Les crochets signifient "optionnel" 
  - Par exemples:
   ** `3 cut` ; efface le troisième fichier.
   ** `3`  ; l'utilisateur désigne le troisième élément du répertoire.
  - Si l'utilisateur ne place pas de NER, c'est le dernier NER utilisé qui sera utilisé pour une commande qui en nécessite. Exemple `visu`
  - Les commandes du gestion de fichiers à implémenter sont:
    - `[<NER>] copy`
    - `past`  ; si l’élément existe, alors le nom du nouvel élément sera concaténé avec "-copy"
    - `[<NER>] cut`
    - `..` ; pour remonter d'un cran dans le système de fichiers
    - `[<NER>] .` ; pour entrer dans un répertoire à condition que le NER désigne un répertoire. Exemple "4 ."
    - `mkdir <nom>` ; pour créer un répertoire
    - `[<NER>] visu` ; permet de voir le contenu d'un fichier texte. Si le fichier n'est pas de type texte, vous afficherez sa taille.
    - `find <nom fichier>` ; Recherche dans toutes les sous répertoires du répertoire courant, le(s) fichier(s) et les affiches.

* L'application permettra à l'utilisateur d'annoter un ER
  - l'annotation consiste à ajouter ou retirer un texte associé à un ER. 
  - Par exemples:
       ** 3 + "ceci est un texte" ; le texte est ajouté ou concaténé au texte existant sur l'ER
       ** 3 -  ; retire tout le texte associé à l'ER 3

 

== Description de l'application à réaliser

* L'interface proposera une visualisation du répertoire courant en mode texte en quatre parties. La partie:
  . présente le cheminement depuis la racine du système de fichier de votre système de fichier.
  . affiche la note associée à l'élément courant NER si elle existe. L'élément courant correspond à la désignation du NER par l'utilisateur ou désigné dans la dernière commande utilisée. Exemple `3 copy`, 3 devient l'élément courant.
  . affiche les ER du répertoire avec leurs NER
  . présente un prompt invitant l'utilisateur à saisir une des commandes présentées ci-dessus.

* Une interface spécifique pourra être proposée pour des situations particulières (visualiser le contenu d'un fichier, une aide, ...).

* Toutes les notes associées aux éléments du répertoire courant seront stockés dans un seul fichier appelé "notes" dans le répertoire courant. Ce fichier peut contenir des objets "sérialisés" ou d'autres formats.



== Références
* Article Wikipedia https://fr.wikipedia.org/wiki/Gestionnaire_de_fichiers[Gestionnaire de fichiers]

* Quelques bibliothèques :
http://fusesource.github.io/jansi/[JAnsi] (couleur dans un terminal),
https://github.com/jline/jline3[JLine] (gestion des saisies)

== Manuel utilisateur

> À compléter :
> Comment l'utilisateur peut savoir quelle commande taper pour un élément du répertoire désigné ?
> Quelles sont les mises à jours du fichier des annotations à effectuer en fonction des types de commandes ?
> Y a t il des bibliothèques Java qui permettront de prendre en charge la visualisation d'une image png si l'utilisateur veut l'afficher ? 
> Quelles sont les commandes qui seraient utiles de rajouter ?
> Quelles améliorations peut on envisager pour rendre l'usage de l'interface clavier plus souples/efficaces pour l'utilisateur ?
> Quelles évolutions peut-on envisager ?

== Manuel technique
=== Compiler le projet
.Sous Linux
----
$ ./mvnw package
----

.Sous Windows
----
> mvnw.cmd package
----

=== Exécuter l'application
----
$ java -jar target/explorer-1.0.jar
----

> À compléter :


> Comment consulter le rapport de couverture de code par les tests ?

Pour consulter le rapport de couverture de code par les tests, il faut se rendre dans le dossier target/site/jacoco/index.html et ouvrir le fichier index.html avec un navigateur web.  Le rapport de couverture de code par les tests est disponible dans la partie "Classses" du rapport. et on utilise cette commande pour genere le fichier dans target  : mvn clean jacoco:prepare-agent install jacoco:report

> Quel est le rôle des différentes classes ?

App.java : 
- Crée un terminal
- Construit un object de la classe Directory à partir du répertoire courant
- Donne l’information sur le NER actuel
- Récupère la saisie de l’utilisateur
- Vérifie qu’elle correspond bien à un commande réalisable 
- Execute la fonction associée à la saisie de l’utilisateur 
- Elle représente la boucle principale du code qui permet de relancer des commandes tant que l’utilisateur le souhaite.

Directory.java : 
- Permet de créer un répertoire
- Permet de se déplacer d’un répertoire à l’autre
- Permet de récupérer le path du répertoire courant
- Permet la gestion des NER et par conséquent permet l’association entre un NER et un élément du répertoire
- Un répertoire est composé d’un chemin et d’une Hashmap
    - La Hashmap a pour clé les NER et pour valeur les éléments du répertoire
- Ainsi il est possible de récupérer un NER associé à un fichier

Afficheur.java :
- Le seul but de cette classe est de récupérer le répertoire courant (sa Hashmap ) et d’afficher sur le terminal le contenu de la Hashmap. Les notes associées à chaque éléments s’il en existe seront affichées. Un répertoire est affiché en bleu et un fichier est affiché en rouge

NoteManager : 
- Gère l’intégralité des opération sur le fichier JSON du répertoire. 
- Création du Json
- Ajout d’une note
- Suppression d’une note
- Mettre à jour le NER d’une note lorsqu’un fichier avec un NER plus petit  (ou plus grand) est ajouté
- - SI une note est supprimée et que le JSON est vide alors le JSON est supprimé
- Trie les notes (permet un accès séquentiel des notes plus rapide si le NER est petit) La recherche reste tout de même en O(n) 

NoteEntry : 
- Chaque note est un objet ainsi chaque opération présenté dans le NoteManager vont justement traiter le JSON à partir des objets NoteEntry qui composent le fichier JSON

CommandManager : 
- Contient l’intégralité des commandes de demandé dans le sujet : 
    - Mkdir crée un répertoire
    - Cut/Copy enregistre un fichier dans le press papier
    - Past colle le fichier/repertoire qui se trouve dans le press papier
        - Si un cut est fait auparavant alors l’élément source est supprimé
        - Propose systématiquement de renommer le fichier (au lieu de mettre -copy par défaut)
    - Find affiche le path de tous les éléments qui ont le même nom que le fichier demandé
    - Visu affichele contenu si c’est un txt sinon, affiche la taille
- Des fonctions intermédiaires sont utilisées pour faire fonctionnels certaines fonctions présentées juste au dessus : 
    - getExtension qui récupère l’extension d’un fichier pour le Visu
    - getDirectorysize qui récupère la taille du répertoire pour Visu
    - generateUniqueElementNumber pour construire la Hashmap de la fonction copyCut 
    - copyDirectoryContents qui récupère l’élément dans le presse papier pour les copier dans le répertoire destination 

> Quels traitements sont réalisés pour gérer une commande saisie par l'utilisateur ? Donnez un exemple.

l utilisateur peut lancer n’importe quelle commande avec n’importe quel NER. Toutefois il se peut que la fonction n’effectue rien. 
Exemple si l’utilisateur souhaite supprimer une note pour un NER qui n’a pas de notes alors il pourra le faire mais cela ne fera rien.


> Quelles améliorations peut-on envisager ?  

Les amélioration a envisager sont les suivantes :

Lorsque le past à lieu nous aimerions pouvoir écraser le fichier possédant le même nom au lieu de ne pouvoir que rajouter un l’élément après l’avoir renommé.

Ajouter une commande qui permet de créer des fichiers txt
Ajouter un commande qui permet de supprimer des elements du repertoire ( fichier/repertoire )
Ajouter une commande qui permet de créer un dossier compressé
Ajouter une commande help qui afficher l’intégralité des commandes prises en charge par l’application. (Comme le man sur linux)
Ajouter une commande qui montre les droits qui nous sont accordés à l’utilisateur pour un element de NER (ou tous)
Permettre de visualiser des elements sur page plutôt que dans le terminal (txt ou autre)
Ajouter un commande Grep qui permet si un element est un fichier, de lire le contenu du fichier et de retourner toutes les lignes qui contiennent le motif recherché.

Permettre un affichage en sur plusieurs lines des notes pour un fichier (Si la note est trop longue il fait déplacer sur le coté pour tout voir)
Ajouter une saisie des commandes plus permissive à l’utilisateur car si la commande est précédée d’un espace elle ne se lance pas car le regex ne la reconnait pas.
Ajouter une auto-complétion des commandes lors de la saisie.
Permettre à l’utilisateur de pouvoir lancer des commandes sur des elements de répertoire qui ne sont pas du répertoire courant.
Mettre en sur-brillance le NER sélectionné plutôt  que de faire un print de l’élément
Et par consequent utiliser la librairie Jansi pour faire un affichage plus propre que l’affichage actuel.
Ajouter un système de vérification de copy cut pour ne pas déplacer ou couper des fichiers sensibles